# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WGRichTextEditor' do

  
pod 'Masonry'
pod 'TZImagePickerController', '~> 3.1.5'
pod 'SVProgressHUD', '~> 2.2.5'

end
